django/api/urls.py
from django.urls import path, include
from api.models import CategoryResource, CourseResource
from tastypie.api import Api

api = Api(api_name='v1')
api.register(CategoryResource())
api.register(CourseResource())

app_name = 'api'

urlpatterns = [
    path('', include(api.urls), name='index'),
]

django/base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # (Название, model.view, параметри)
    path('my-panel/', admin.site.urls),
    # path('shop/', include('shop.urls')),
    path('', include('shop.urls')),
    # path('api/', include('api.urls')),

]

django/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # (Название, model.view, параметри)
    path('', views.index, name='index'),
    path('<int:course_id>', views.course, name='course'),
]

django/api/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from .auth import CustomAuthentication
from tastypie.authorization import Authorization


# Create your models here.
class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name: str = 'categories'
        allowed_methods: list = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name: str = 'courses'
        allowed_methods: list = ['get', 'post', 'delete']
        excludes: list = ['created_at', 'reviews_dty']
        authentication: CustomAuthentication = CustomAuthentication()
        authorization: Authorization = Authorization()

    # Эти манипуляции для того что бы добавить категорию к курсу, поскольку они связаны каскадно
    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category
        return bundle

    # Сделать title заглавными, так можна пересчитывать цену к примеру
    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

django/shop/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_dty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title + ' (' + str(self.students_qty) + ')'

django/api/views.py
from django.shortcuts import render

# Create your views here.

django/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course


# Create your views here.
def index(request) -> render:
    courses: Course = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses, 'title': 'All Courses'})


def course(request, course_id) -> render:
    # Option 1
    # try:
    #     course: Course = Course.objects.get(pk=course_id)
    #     return render(request, 'course.html', {'course': course, 'title': course.title})
    # except Course.DoesNotExist:
    #     raise Http404()

    # Option 2
    course: get_object_or_404 = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/course.html', {'course': course, 'title': course.title})

django/templates/shop/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <a href="{% url 'shop:index' %}" class="navbar-brand">Courses Shop</a>
        <span>
               <a href="/my-panel/" class="navbar-brand">My panel</a>
               <a href="/api/v1/" class="navbar-brand">Api doc</a>
        </span>
    </div>
</nav>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

django/templates/shop/course.html
{% extends 'shop/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1 class="mt-5">{{course.title}}</h1>
<h2>{{course.category}}</h2>
<p>Price: {{course.price}}</p>
<p>Students: {{course.students_qty}}</p>
<button class="btn-primary">Buy</button>
{% endblock %}

django/templates/shop/courses.html
{% extends 'shop/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
    <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Price</th>
        <th>Students Quantity</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for course in courses %}
    <tr>
        <td>
<!--            <a href="{{course.id}}">{{course.title}}</a>-->
            <a href="{% url 'shop:course' course.id %}">{{course.title}}</a>
        </td>
        <td>{{course.category}}</td>
        <td>{{course.price}}</td>
        <td>{{course.students_qty}}</td>
        <td>
            <button class="btn btn-primary">Buy</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}